{{- if .Values.gitRepo.url }}
# ArgoCD self-management Application
# This Application manages ArgoCD itself, separate from the ApplicationSet
# ArgoCD is bootstrapped via Helm, then this Application takes over for ongoing sync
#
# NOTE: This is intentionally NOT a Helm hook - it should persist as a regular resource
# so ArgoCD can self-manage. Using hooks would cause it to be marked for pruning.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    # Use sync-wave to ensure CRDs are ready before this Application is created
    argocd.argoproj.io/sync-wave: "5"
  # No finalizer - prevents deletion deadlock during self-management
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo.url }}
    targetRevision: {{ .Values.gitRepo.revision }}
    path: {{ .Values.gitRepo.path }}/infra/argocd
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.clusterName }}.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false  # Don't prune - prevents self-deletion issues
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
