{{- if .Values.gitRepo.url }}
# ApplicationSet for all infrastructure apps
# Auto-discovers apps in apps/infra/* directory
# To add a new infra app: create apps/infra/<app-name>/ with Chart.yaml, values.yaml, and values-<cluster>.yaml files
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
  annotations:
    # Helm hooks ensure this is created AFTER ArgoCD CRDs are installed
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitRepo.url }}
        revision: {{ .Values.gitRepo.revision }}
        directories:
          - path: {{ .Values.gitRepo.path }}/infra/*
          # Exclude the argocd chart itself to avoid circular dependency during initial bootstrap
          # ArgoCD is initially installed via Helm, then self-manages through this ApplicationSet
  template:
    metadata:
      name: '{{`{{ path.basename }}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.gitRepo.url }}
        targetRevision: {{ .Values.gitRepo.revision }}
        path: '{{`{{ path }}`}}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{ .Values.clusterName }}.yaml
          # Skip missing per-cluster values files - allows apps to work with just values.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{ path.basename }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
