{{- if .Values.gitRepo.url }}
# ApplicationSet for all infrastructure apps
# Auto-discovers apps in apps/infra/* directory via app-config.yaml files
# To add a new infra app: create apps/infra/<app-name>/ with Chart.yaml, values.yaml, app-config.yaml, and optionally values-<cluster>.yaml files
# To scope an app to specific clusters: edit app-config.yaml and set target-<cluster>: "true" or "false"
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.gitRepo.url }}
        revision: {{ .Values.gitRepo.revision }}
        files:
          - path: {{ .Values.gitRepo.path }}/infra/*/app-config.yaml
        # Filter apps based on target-<cluster> keys in app-config.yaml
        # Only apps with target-<clusterName>: "true" will be generated
        selector:
          matchLabels:
            target-{{ .Values.clusterName }}: "true"
  template:
    metadata:
      name: '{{ `{{ index .path.segments 2 }}` }}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.gitRepo.url }}
        targetRevision: {{ .Values.gitRepo.revision }}
        path: '{{ `{{ .path.path }}` }}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{ .Values.clusterName }}.yaml
          # Skip missing per-cluster values files - allows apps to work with just values.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{ index .path.segments 2 }}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
