{{- if .Values.gitRepo.url }}
# ApplicationSet for workload applications
# Uses Git files generator to discover apps in apps/workloads/ via app-config.yaml files
# To add a new workload: create apps/workloads/<app-name>/ with Chart.yaml, values.yaml, and app-config.yaml
# Optionally add values-<cluster>.yaml for cluster-specific overrides
# To scope an app to specific clusters: edit app-config.yaml and list only the desired clusters in targetClusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
  annotations:
    # Sync wave ensures CRDs are ready before ApplicationSet is applied
    argocd.argoproj.io/sync-wave: "5"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.gitRepo.url }}
        revision: {{ .Values.gitRepo.revision }}
        files:
          - path: {{ .Values.gitRepo.path }}/workloads/*/app-config.yaml
  template:
    metadata:
      name: '{{ `{{ index .path.segments 2 }}` }}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.gitRepo.url }}
        targetRevision: {{ .Values.gitRepo.revision }}
        path: '{{ `{{ .path.path | dir }}` }}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{ .Values.clusterName }}.yaml
          # Skip missing per-cluster values files - allows apps to work with just values.yaml
          ignoreMissingValueFiles: true
          # Pass cluster info to workloads for auto-generating ingress hostnames
          parameters:
            - name: clusterName
              value: {{ .Values.clusterName }}
            - name: domainSuffix
              value: {{ .Values.domainSuffix }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{ index .path.segments 2 }}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  # Only generate Application if this cluster is in the app's targetClusters list
  templatePatch: |
    {{ `{{- if not (has "` }}{{ .Values.clusterName }}{{ `" .targetClusters) }}` }}
    {{ `{{ fail "skip" }}` }}
    {{ `{{- end }}` }}
{{- end }}
